id: P008179
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22418
  title: མངོན་རྟོགས་རྒྱན་གྱི་རྣམ་བཤད་ཚིག་དོན་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  volumes:
    a6ab2b25f26e464f8c122204658623de:
      image_group_id: I1KG22461
      title: ''
      volume_number: 1
      total_pages: 102
